baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "wageneder.mx"
  subtitle    = "Personal Blog of Wageneder Max"

  cover       = "pictures/MW.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "mwageneder"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Max Wageneder"
  authorAvatar = "pictures/MW.jpg"
  authorLocation = "Graz, Austria"
  authorWebsite = "https://eueung.github.io"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tech Blog"
  url = "/tags/tech/"
  weight = 100

[[menu.main]]
  name = "Diabetes Blog"
  url = "/categories/diabetes/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.at"
  weight = 95